
skillMetadata:
  sections:
    - name: Connection details
      fields:
        - name: mqtt_host
          type: text
          label: MQTT Host Server
          value: "101.181.46.180"
        - name: badge_id
          type: text
          label: Badge ID
          value: ""
          placeholder: esp32_xxxxxxxxxxxx
